// Canonical public origin. Production serves `www.reelcaster.com`; the apex
// redirects to it, so every canonical, OG url, and sitemap entry must use the
// www host — pointing a canonical at a URL that redirects is a self-inflicted
// signal conflict.
//
// This is the single source of truth. Do not re-declare a SITE_URL constant in
// a page file; import from here so the host can never drift page to page.
export const SITE_URL = "https://www.reelcaster.com";

export const SITE_NAME = "ReelCaster";

// Public support inbox. Same reasoning as SITE_URL: this address is quoted in
// JSON-LD, on the legal pages, in support email headers, and in every mailto:
// fallback, so it gets one home rather than a copy per page.
export const SUPPORT_EMAIL = "support@reelcaster.com";

/**
 * Site-wide social card, generated by src/app/opengraph-image.tsx.
 *
 * A page that declares its own `openGraph` block REPLACES the inherited one
 * rather than merging into it, so the file-convention image silently vanishes
 * from exactly the pages that bothered to write custom OG copy. Any page
 * setting `openGraph` must therefore name its images explicitly — spread
 * `DEFAULT_OG` for the standard card, or list your own.
 *
 * Relative paths resolve against `metadataBase` (set in the root layout).
 */
export const DEFAULT_OG_IMAGE = "/opengraph-image";

export const DEFAULT_OG = {
  images: [{ url: DEFAULT_OG_IMAGE, width: 1200, height: 630 }],
};

/** Absolute URL for a site-relative path (`/pricing` → `https://…/pricing`). */
export function siteUrl(path = "/"): string {
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

type Crumb = { name: string; path: string };

/**
 * schema.org BreadcrumbList. Pass the trail in order, root first; the last
 * entry is the current page. Positions are 1-indexed per the spec.
 */
export function breadcrumbJsonLd(crumbs: Crumb[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: crumbs.map((c, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: c.name,
      item: siteUrl(c.path),
    })),
  };
}

/** Site-wide publisher identity, referenced by `publisher`/`provider` nodes. */
export const ORGANIZATION_JSONLD = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "@id": `${SITE_URL}/#organization`,
  name: SITE_NAME,
  url: SITE_URL,
  logo: `${SITE_URL}/reelcaster-logo.svg`,
  email: SUPPORT_EMAIL,
  areaServed: [
    // Only regions with published cities — see COVERED_PROVINCES. Claiming a
    // service area we can't forecast is a promise made to Google.
    { "@type": "AdministrativeArea", name: "British Columbia" },
    { "@type": "AdministrativeArea", name: "Washington" },
  ],
};
